version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    target-branch: dev
  - package-ecosystem: npm
    directory: "/src/language-service"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    target-branch: dev
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    open-pull-requests-limit: 10
    target-branch: dev
